stages:
    data_ingestion:
        cmd: python ./src/data/data_ingestion.py

        deps:
        - ./src/data/data_ingestion.py

    build_features:
        cmd: python ./src/features/build_features.py

        deps:
        - ./src/features/build_features.py

        params:
        - build_features.mini_batch_kmeans.n_clusters
        - build_features.mini_batch_kmeans.n_init
        - build_features.mini_batch_kmeans.random_state
        - build_features.ewma.alpha

        outs:
        
        - ./models/scaler.joblib
        - ./models/mb_kmeans.joblib


    extract_feature:
        cmd: python ./src/features/extract_feature.py

        deps:
        - ./src/features/extract_feature.py
        - ./data/processed/resampled_data.csv


        outs:
        - ./data/processed/train_data.csv
        - ./data/processed/test_data.csv



    train_model:
        cmd: python ./src/models/train_model.py  ./data/processed/train_data.csv ./data/processed/test_data.csv 
        deps:
        - ./src/models/train_model.py
        - ./data/processed/train_data.csv
        - ./data/processed/test_data.csv

        outs:
        - ./models/best_model.joblib
        - ./models/encoder.joblib